Update reusable.yml

diff --git a/.github/workflows/reusable.yml b/.github/workflows/reusable.yml
--- a/.github/workflows/reusable.yml
+++ b/.github/workflows/reusable.yml
@@ -15,4 +15,11 @@ jobs:
     - id: toggle
       run: |-
         echo "Enabled: ${{ inputs.enable }}"
+  job-to-fail:
+    runs-on: ubuntu-latest
+    steps:
+    - id: fail
+      run: |-
+        echo "Failure expected"
+        exit 1;
  
